Important Database Changes
 When I ran all the tests simultaneously i received the following exception:
       java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30005ms.

 It turned out that I wasn't calling the close() method of the Connection object and the pool didn't have available connections anymore.
 This is why I've decided to return the Connection directly from the database so i will be able to close it. I realised that all my old methods in Database were useless since they were hiding the Connection object from me ( which was my initial idea ) . After that the methods could only convert SqlException to RuntimeException, but this wasn't really necessary  anymore.